(source (official cli))
(config username "Thibaut Mattio")
(config project_name "OCaml Migrate")
(config email thibaut.mattio@gmail.com)
(config npm_username tmattio)
(config github_username tmattio)
(config project_description "Database migrations for Reason and OCaml")
(config package_manager Opam)
(config ci_cd Github)
(config syntax OCaml)
(config project_snake omigrate)
(config project_slug omigrate)
(config test_framework Alcotest)
